version: "3"
services:
  toasty:
    container_name: toasty-server
    restart: always
    build: .
    ports:
      - "5000:5000"
    links:
      - mongo
  mongo:
    container_name: toasty-mongo
    image: mongo:4.0.6-xenial
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
